apiVersion: v1
kind: Secret
metadata:
  name: bitwarden-secret
  namespace: bitwarden
type: Opaque
data:
  globalSettings__installation__id: ODZmOTZmYmItMzE3Ny00ZjNiLWIzZjUtYjI0ZjAxMDFlYjlh
  globalSettings__installation__key: ektFd3ZuY2tzeFVkMjlDMHR4Rkk=
  adminSettings__admins: ZHVuZ2J1aS5kdW5nYnVpLjAwQGdtYWlsLmNvbQ==