apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: goclaw-data-pvc
  namespace: goclaw
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
