ports:
   web:
      port: 80
      exposedPort: 80
      redirections:
         entryPoint:
            to: websecure
            scheme: https
            permanent: true
   websecure:
      port: 443
      exposedPort: 443

service:
   externalIPs:
      - <MASTER_VPS_PUBLIC_IP>

ingressRoute:
   dashboard:
      enabled: true
      matchRule: Host(`traefik.dungxbuif.com`)
      entryPoints: ['websecure']
      middlewares:
         # - name: authentik-forward-auth  # Removed Authentik middleware
         - name: traefik-dashboard-auth  # Enabled basic auth middleware

securityContext:
   capabilities:
      drop: [ALL]
      add: [NET_BIND_SERVICE]
   readOnlyRootFilesystem: true
   runAsGroup: 0
   runAsNonRoot: false
   runAsUser: 0
