apiVersion: v1
kind: Secret
metadata:
  name: gitlab-object-storage
  namespace: gitlab
type: Opaque
stringData:
  connection: |
    provider: AWS
    region: us-east-1
    aws_access_key_id: admin
    aws_secret_access_key: "<MINIO_PASSWORD>"
    host: minio-service.minio-system.svc.cluster.local
    endpoint: http://minio-service.minio-system.svc.cluster.local:80
    path_style: true
    aws_signature_version: 4
    use_ssl: false

---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-registry-storage
  namespace: gitlab
type: Opaque
stringData:
  config: |
    s3:
      region: us-east-1
      bucket: gitlab-registry
      accesskey: admin
      secretkey: "<MINIO_PASSWORD>"
      regionendpoint: http://minio-service.minio-system.svc.cluster.local:80
      pathstyle: true
      v4auth: true
      secure: false

---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-minio-secret
  namespace: gitlab
type: Opaque
stringData:
  accesskey: admin
  secretkey: "<MINIO_PASSWORD>"

---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-initial-root-password
  namespace: gitlab
type: Opaque
stringData:
  password: "<GITLAB_ADMIN_PASSWORD>"
