- name: Create Kubernetes manifests directory
  ansible.builtin.file:
    path: /etc/kubernetes/manifests
    state: directory
    mode: "0755"

- name: Install kube-vip static pod manifest
  ansible.builtin.template:
    src: kube-vip.yaml.j2
    dest: /etc/kubernetes/manifests/kube-vip.yaml
    mode: "0644"
