[k8s_control_plane]
k8s-cp-1 ansible_host=<K8S_CP1_IP> ansible_user=ubuntu
k8s-cp-2 ansible_host=<K8S_CP2_IP> ansible_user=ubuntu
k8s-cp-3 ansible_host=<K8S_CP3_IP> ansible_user=ubuntu

[k8s_first_control_plane]
k8s-cp-1 ansible_host=<K8S_CP1_IP> ansible_user=ubuntu

[k8s_join_control_plane]
k8s-cp-2 ansible_host=<K8S_CP2_IP> ansible_user=ubuntu
k8s-cp-3 ansible_host=<K8S_CP3_IP> ansible_user=ubuntu

[k8s_cluster:children]
k8s_control_plane

[k8s_cluster:vars]
kube_vip=<K8S_VIP>
kube_control_plane_endpoint=<K8S_VIP>:6443
