#!/bin/bash
# Master Deployment Script for Homelab K8s on Proxmox
# Autogenerated for fully automated agent-supervised deployment.

set -e

# --- Colors for better UX ---
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_err() { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

# --- Check Prerequisites ---
log_info "Checking prerequisites..."
command -v terraform >/dev/null 2>&1 || log_err "Terraform is not installed."
command -v ansible >/dev/null 2>&1 || log_err "Ansible is not installed."

# --- Configs ---
IAC_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PVE_HOST="<PROXMOX_IP>"
TEMPLATE_ID=9000
PVE_PASS="<PROXMOX_ROOT_PASSWORD>"

# Extract API Token from terraform.tfvars
PVE_TOKEN_ID=$(grep "pm_api_token_id" "$IAC_DIR/terraform/terraform.tfvars" | cut -d'"' -f2)
PVE_TOKEN_SECRET=$(grep "pm_api_token_secret" "$IAC_DIR/terraform/terraform.tfvars" | cut -d'"' -f2)

# --- Phase 1: Proxmox Template ---
log_info "Phase 1: Verifying Proxmox Template (ID $TEMPLATE_ID) via API..."

# Check if template exists using Proxmox API
TEMPLATE_EXISTS=$(curl -k -s -H "Authorization: PVEAPIToken=$PVE_TOKEN_ID=$PVE_TOKEN_SECRET" \
    "https://$PVE_HOST:8006/api2/json/nodes/pve/qemu/$TEMPLATE_ID/status/current" | grep -c "data" || true)

if [ "$TEMPLATE_EXISTS" -eq 0 ]; then
    log_warn "Template $TEMPLATE_ID not found via API. Creating it now via SSH..."
    export SSHPASS=$PVE_PASS
    sshpass -e scp -o StrictHostKeyChecking=no -o IdentitiesOnly=yes "$IAC_DIR/create_template.sh" root@$PVE_HOST:/root/create_template.sh
    sshpass -e ssh -o StrictHostKeyChecking=no -o IdentitiesOnly=yes root@$PVE_HOST "bash /root/create_template.sh"
    log_info "Template creation complete."
else
    log_info "Template $TEMPLATE_ID exists. Skipping creation."
fi

# --- Phase 2: Terraform Infrastructure ---
log_info "Phase 2: Provisioning VMs with Terraform..."
cd "$IAC_DIR/terraform"

if [ ! -f "terraform.tfvars" ]; then
    log_err "terraform.tfvars not found. Please ensure it is configured with API tokens."
fi

terraform init
terraform apply -auto-approve

log_info "Terraform provisioning complete. Waiting for VMs to boot and Cloud-Init to finish..."
# Wait a bit for Cloud-Init to set up SSH keys
sleep 30

# --- Phase 3: Ansible Configuration ---
log_info "Phase 3: Configuring Kubernetes Cluster with Ansible..."
cd "$IAC_DIR/ansible"

# Ensure inventory is generated by terraform
if [ ! -f "inventory.ini" ]; then
    log_err "inventory.ini not found. Terraform might have failed to generate it."
fi

# Ping nodes to ensure they are reachable
log_info "Testing SSH connectivity to nodes..."
ansible k8s_cluster -m ping

# Run the master playbook
ansible-playbook site.yml

log_info "===================================================="
log_info "Deployment Successful!"
log_info "Kubeconfig is available on the first control-plane node."
log_info "You can access the cluster at: https://<K8S_VIP>:6443"
log_info "===================================================="
